SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListaUtenti](
	[IdUtente] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
	[Image] [nvarchar](500) NULL,
	[Admin] [bit] NOT NULL,
	[NomeUtente] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ListaUtenti] ADD  CONSTRAINT [PK_ListaUtenti] PRIMARY KEY CLUSTERED 
(
	[IdUtente] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[ListaUtenti] ADD  CONSTRAINT [IX_ListaUtenti] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ListaUtenti] ADD  CONSTRAINT [DF_Admin]  DEFAULT ((0)) FOR [Admin]
GO
ALTER TABLE [dbo].[ListaUtenti] ADD  CONSTRAINT [DEFAULT_ListaUtenti_NomeUtente]  DEFAULT (user_name()) FOR [NomeUtente]
GO
