SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CategoriaProdotti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Categoria] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CategoriaProdotti] ADD  CONSTRAINT [PK_NewTable] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
